### ISSUE TITLE
Error using acquisitionGUI.py

### ISSUE THREAD

**Issue by dreathe** [labcif/ADB-Extractor#2]
While using the gui interface (acquisitionGUI.py ) i came across the following error, noone of the aquisitions using this method work for me. 

adb: error: failed to access 'dados/com.google.android.apps.authenticator2.apk': No such file or directory

While the command line works as intended, aquisition script (acquisition.py):
##python3 acquisition.py -a com.google.android.apps.authenticator2 -d "physical" -t private

[Info ] Acquiring from device: USB
[Info ] Host OS: POSIX                                                                                                      
[Info ] Checking if com.google.android.apps.authenticator2 exists...                                                        
[Info ] Yes!                                                                                                                
[Info ] Getting application version...                                                                                      
[Info ] Getting Android Version...                                                                                          
[Info ] com.google.android.apps.authenticator2 version: 6.0                                                                 
[Info ] Android version: 9                                                                                                  
[Info ] Copying data from com.google.android.apps.authenticator2 version 6.0 ...                                            
[Info ] Acquiring private data                                                                                              
[Info ] Copying to local storage ...                                                                                        
[Info ] Compressing com.google.android.apps.authenticator2-v6.0-private--usb9-u0--20230621-221510.tar ...                   
[Info] Compressing Terminated.                                                                                              
[Info ] Copying to local storage ...                                                                                        
[Info ] Copy Terminated.                                                                                                    
[Info ] Cleaning acquisition files from phone...                                                                            
[Info ] Clean Terminated.                                                                                                   
[Done ] Operation Completed with success, generated file: com.google.android.apps.authenticator2-v6.0-private--usb9-u0--20230621-221510.tar.gz

**Comment by fabian-nunes** [comment]
I am going to look in the issue, i tested it now in both my windows machines and macos and could not replicate error (used and emulator but will later test it with my rooted device). At first I suspected the error could be of the Android Version (9 and prior had a different location for the apk files), however I also tested it in a emulator Version 9. 
<img width="800" alt="Captura de ecrã 2023-06-22, às 12 35 33" src="https://github.com/labcif/ADB-Extractor/assets/54534495/9d799a8b-aa6a-4bdd-8ac6-df154def7ae5">
<img width="800" alt="Captura de ecrã 2023-06-22, às 12 58 44" src="https://github.com/labcif/ADB-Extractor/assets/54534495/ad4ead75-3670-439a-a398-067afd4a3dc2">

What phone are you using?

**Comment by dreathe** [comment]
I tried to replicate the error, and everything worked today, not sure why it didn't yesterday. 
But i was getting the correct confirmation "extraction completed" aswell, and all the operations were successful, also no  output was generated on the output directory. 

But since everything works and i cannot duplicate the same error as yesterday, i have nothing else to say. Thanks for all the work on this tool.  

 Brand: Xiaomi
 Model: Redmi Note 3;
 CPU: Snapdragon (Qualcomm Technologies, Inc MSM8956);
 CodeName: Kenzo;
 Arquitecture: Armv8 - aarch64;
 Kernel Version: Linux version 3.10.108 Escrima X28 Kamui LightningBlade PurpleLightning;
 Android: 9.0 (Pie);
 SDK: 28;
 OS: PixelExperience aosp;
 OS version: 20190906-0737-OFFICIAL;
 Build: PQ3A.190801.002;

**Comment by dreathe** [comment]
i found out why i wasn't getting no output. The output directory had special characters in her name. That was the reason why it didnt work.
